#!/bin/sh

#export PROMPT_COMMAND='PS1=`echo "\n\[\e[0;33m\][\D{%d.%m.%Y %H:%M:%S}] \[\e[01;31m\]\u@\h:\$ORACLE_SID \[\e[1;34m\]\w\n\$ \[\e[0;32m\]\[\e[0m\]"`'

#aliases=/etc/profile.d/00-dbs-aliases.sh
#if [ -s $aliases ]; then
#  . /etc/profile.d/00-dbs-aliases.sh
#fi

P1_=$1
shift
args=$*
# args=`echo $args | tr '$' '~'`
args=$(echo $args | sed  's|\$|\\$|g')
BASEDIR=`dirname $0`
wtpi="$BASEDIR/tpi"

# echo "host: "$P1_
# echo "args: "$args
# alias | grep "$P1_"

case "$P1_" in
 s-dtln-wmsdb*|db06.wms.korablik.ru)
#   cat $wtpi | eval $P1_ "sudo -i -u oracle /bin/sh -s $args"
   cat $wtpi | ssh  $P1_ "sudo -i -u oracle /bin/sh -s $args"
   ;;
 storgco|ikb)
   $wtpi $P1_ $args
   ;;
 [0-9]*)
   cat $wtpi | ssh $P1_ "/bin/sh -s $args"
   ;;
 [z]14-*|p260unc*|10.35.17.5)
#        echo "args:"$args
         args2=$(echo "$args" | sed  's|\$|\\\\$|g')
#        echo "args2:"$args2
#   cat $wtpi | ssh -o ServerAliveInterval=30 dbservice@172.16.83.38 -t ssh -o ServerAliveInterval=30 -l oracle $P1_ "/bin/sh -s $args"
#   cat $wtpi | eval ssh -o ServerAliveInterval=30 t.mukhametshin@172.16.83.38 -t ssh -o ServerAliveInterval=30 -l oracle $P1_ '/bin/sh -s $args2'
    cat $wtpi | ssh $P1_ "/bin/sh -s $args"
   ;;
 jet)
	 UNAME=`uname | awk -F_ '{print $1}'`
	 if [ "$UNAME" = "CYGWIN" ]; then 
             cat $wtpi | ssh -J amazon1 oracle@$P1_ "/bin/sh -s $args"
	 else
             cat $wtpi | ssh oracle@$P1_ "/bin/sh -s $args"
	 fi
 ;;
 *) #alias $P1_ >/dev/null 2>&1
    #rc=$?
    #if [ "$rc" -eq 0 ]; then
    #  cat $wtpi | eval $P1_ '/bin/sh -s $args'
    #else
      cat $wtpi | ssh oracle@$P1_ "/bin/sh -s $args"
    #fi
   ;;
esac

exit

#######################################################

host=$1
HST=$host
# HST=`awk '$2=="'$host'"{print $1}' /app/start/etc/hosts`
# if [ "$HST" = "" ]; then
#  HST=$host
# fi
shift
args=$*

case $host in
  askona*|192.168.1.132|192.168.1.131) username=grid ;;
  *) username=oracle ;;
esac

cat ~/tal/tpi | ssh $username@$HST "/bin/sh -s $args"

exit

