#!/bin/bash

SRV=$1
shift
args=$*

args=$(echo $args | sed  's|\$|\\$|g')
# args=$(echo $args | sed  's|-|=|g')
BASEDIR=`dirname $0`
wtps="$BASEDIR/tps"



#cat tps | ssh $SRV "sudo su - postgres"

cat $wtps | ssh $SRV "sudo -i -u postgres /bin/bash -s $args"

