#!/bin/bash

SRV=$1
shift
# args=$*
args="$@"
args=$(echo $args | sed -e 's|\$|\\$|g' -e 's|(|\\(|g' -e 's|)|\\)|g' -e 's|"|\\"|g')

BASEDIR=`dirname $0`
wtps="$BASEDIR/tps"



#cat tps | ssh $SRV "sudo su - postgres"

cat $wtps | ssh $SRV "sudo -i -u postgres /bin/bash -s $args"

