#!/bin/bash
set -f

# for t.mukhametshin@db-service.ru
#sender=t.mukhametshin@db-service.ru
#gapp=vngogoshxiqchxsz
#gapp=lqmshqloajirlbrp
# for m.mutate@yandex.ru
sender=m.mutate@yandex.ru
gapp=frwpbgyrpbtahuqw

if [ $# -lt 1 ]; then
  echo "Usage: $0 [-s subject] email [-a attachment_file]"
  exit
fi

while [[ $# > 0 ]]; do
   case "$1" in
      -s) sub="$2" ; shift ;;
      -a) file="$2" ; shift ;;
     *@*) receiver="--mail-rcpt "$1" "$receiver ; shift ;;
       *) shift ;;
  esac
done

#echo "sub="$sub
#echo "receiver="$receiver
receiver_=`echo $receiver | sed 's/--mail-rcpt //g'`
#echo "receiver_="$receiver_
#echo "file="$file

msg=$(cat; echo x)
msg=${msg%x}
#printf %s "$msg"
#echo "$msg"

# send telegram message:
#BASEDIR=`dirname $0`
#TLGRM_CMD=`$BASEDIR/iniget.sh mon.ini.$CLIENT telegram cmd`
#TLGRM_CHT=`$BASEDIR/iniget.sh mon.ini.$CLIENT telegram chat_id`
#$TLGRM_CMD mark0 $TLGRM_CHT "sender: $sender  
#\`$msg\`"

# curl --url "smtps://smtp.yandex.ru:465" --ssl-reqd --mail-from "update@mydomain.ru" --mail-rcpt "update@mydomain.ru" --upload-file fileforsending.txt --user "update@mydomain.ru:PASSWORD" --insecure

if [ -z "$file" ]; then 
    #    --mail-rcpt $receiver \
    curl -s --url 'smtp://smtp.yandex.ru:465' --ssl-reqd \
    --mail-from $sender \
    $receiver \
    --user $sender:$gapp \
     -T <(echo -e "From: ${sender}
To: ${receiver_}
Subject: ${sub}

${msg}")
echo "Mail sent."
else
    # attachment exists condition
    # MIME type for multiple type of input file extensions
    #    --mail-rcpt $receiver\
    MIMEType=`file --mime-type "$file" | sed 's/.*: //'`
    curl -s --url 'smtps://smtp.yandex.ru:465' --ssl-reqd \
    --mail-from $sender \
    $receiver \
    --user $sender:$gapp \
     -H "Subject: $sub" -H "From: $sender" -H "To: $receiver_" -F \
    '=(;type=multipart/mixed' -F "=$msg;type=text/plain" -F \
      "file=@$file;type=$MIMEType;encoder=base64" -F '=)'
echo "Mail sent."
fi

